apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: freeipa
spec:
  minReadySeconds: 10 # by default is 0
  selector:
    matchLabels:
      app: freeipa # has to match .spec.template.metadata.labels
  serviceName: "freeipa"
  replicas: 1
  template:
    metadata:
      labels:
        app: freeipa # has to match .spec.selector.matchLabels
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - freeipa
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: freeipa
          image: quay.io/freeipa/freeipa-server:centos-9-stream-4.12.2
          readinessProbe:
            exec:
              command: ["/usr/bin/systemctl", "is-active", "--quiet", "ipa"]
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /
              port: 80
            # NOTE: if initial installation fails, try increasing this value:
            failureThreshold: 60
            periodSeconds: 30
          env:
            - name: TZ
              value: CST6CDT
            - name: IPA_SERVER_HOSTNAME
              value: "freeipa.clee.private.morphacy.net"

            - name: IPA_SERVER_INSTALL_OPTS
              valueFrom:
                secretKeyRef:
                  name: freeipa-install-secrets
                  key: IPA_OPTIONS

            - name: IPA_SERVER_INSTALL_OPTS
              valueFrom:
                secretKeyRef:
                  name: freeipa-install-secrets
                  key: IPA_REPLICA_OPTIONS
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: freeipa-install-secrets
                  key: IPA_ADMIN_PASSWORD
          args: [ "ipa-replica-install" ]

          securityContext:
            capabilities:
              add:
                - SYS_TIME
                - NET_BIND_SERVICE
            seccompProfile:
              type: Unconfined
          stdin: true
          tty: true
          ports:
            - containerPort: 53 # dns
            - containerPort: 53 # dns
              protocol: UDP
            - containerPort: 80 # http
            - containerPort: 88 # kerberos
            - containerPort: 88 # kerberos
              protocol: UDP
            - containerPort: 123 # ntp
            - containerPort: 123 # ntp
              protocol: UDP
            - containerPort: 389 # ldap
            - containerPort: 443 # https
            - containerPort: 464 # kpasswd
            - containerPort: 464 # kpasswd
              protocol: UDP
            - containerPort: 636 # ldaps
          volumeMounts:
            - name: ipa-data
              mountPath: /data
            # - name: cgroups
            #   mountPath: /sys/fs/cgroup
            # - name: run
            #   mountPath: /run
            # - name: run-systemd
            #   mountPath: /run/systemd
            # - name: tmp
            #   mountPath: /tmp
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 192.168.1.1
          - 8.8.8.8
          - 8.8.4.4
      hostname: "freeipa.clee.private.morphacy.net"
      resources:
        requests:
          memory: "512Mi"
          cpu: "250m"
      terminationGracePeriodSeconds: 10
      volumeClaimTemplates:
        - metadata:
            name: ipa-data
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 1Gi
      # volumes:
      #   - name: cgroups
      #     hostPath:
      #       path: /sys/fs/cgroup
      #   - name: run
      #     emptyDir:
      #       medium: Memory
      #   - name: run-systemd
      #     emptyDir:
      #       medium: Memory
      #   - name: tmp
      #     emptyDir:
      #       medium: Memory
      #   - name: data
